# Do not use this file as example
# It is only to test suite
# Run "pre-commit run -c .pre-commit-config-local.yaml -v --all"
# TODO: Auto-generate from .pre-commit-hooks.yaml
repos:
  - repo: local
    hooks:
      - id: oca-checks-odoo-module
        name: Checks for Odoo modules
        description: Multiple checks for Odoo modules
        entry: oca-checks-odoo-module
        args: []
        language: python
        types_or: ["csv", "markdown", "pofile", "python", "rst", "xml"]
        # require_serial to evaluate the whole module in-one-shot to have full context about other xmlids and so on
        require_serial: true
