- id: oca-checks-odoo-module
  name: Checks for Odoo modules
  description: Multiple checks for Odoo modules
  entry: oca-checks-odoo-module
  args: []
  language: python
  types_or: ["csv", "markdown", "pofile", "python", "rst", "xml"]
  # require_serial to evaluate the whole module in-one-shot to have full context about other xmlids and so on
  require_serial: true
