# Do not use this file as example
# It is only to test suite
# Run "pre-commit run -c .pre-commit-config-local.yaml -v --all"
# TODO: Auto-generate from .pre-commit-hooks.yaml
repos:
  - repo: local
    hooks:
      - id: oca-checks-odoo-module-local
        name: Checks for Odoo modules
        description: Multiple checks for Odoo modules
        entry: oca-checks-odoo-module
        args: []
        language: python
        types: [python]
        files: /\_\_(manifest|openerp)\_\_\.py$
